create table TodoList (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title TEXT,
  todoListId BIGINT DEFAULT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updaetdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (todoListId) REFERENCES TodoList(id) ON DELETE CASCADE
) ENGINE = InnoDB;